# Generated by Django 3.0.2 on 2020-01-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Property Owner', 'Property Owner'), ('Estate Agent', 'Estate Agent'), ('Property Developer', 'Property Developer')], default='Individual', max_length=50),
        ),
    ]
