# Generated by Django 3.0.2 on 2020-01-25 14:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'NGN ₦')], default='NGN', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=14)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('broker_fee', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('address', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_ads.Category')),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/ad/%Y')),
                ('position', models.PositiveSmallIntegerField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_ads.Ad')),
            ],
            options={
                'verbose_name': 'Update Image',
                'verbose_name_plural': 'Update Images',
            },
        ),
    ]
