# Generated by Django 3.0.2 on 2020-02-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_ads', '0002_ad_adimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postition', models.PositiveIntegerField()),
                ('placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Property field',
                'verbose_name_plural': 'Property field',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='fields',
            field=models.ManyToManyField(related_name='category', to='property_ads.AdField'),
        ),
    ]
