# Generated by Django 3.0.2 on 2020-02-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_ads', '0003_auto_20200210_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adfield',
            old_name='postition',
            new_name='position',
        ),
    ]
