# Generated by Django 3.0.2 on 2020-02-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_ads', '0004_auto_20200210_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adimage',
            options={'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
    ]
